version: '3.8'

services:
  # App
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  # DB
  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pexample"]
      interval: 5s
      retries: 15
