version: '3.8'

services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

  db:
    build: db/.
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: world
    ports:
      - "33060:3306"    # or 33061:3306 if you changed it before
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pexample"]
      interval: 3s
      timeout: 20s
      retries: 10
      start_period: 30s